// Generated by typings
// Source: src/app-definitions/whs.d.ts
declare module 'whs' {
  interface IBoxGeometryParameters {
    geometry:{
      width?: number;
      height?: number;
      depth?: number;
      widthSegments?: number;
      heightSegments?: number;
      depthSegments?: number;
    },

    material?: any

    shadow?: {
      receive?: boolean,
      cast?: boolean
    },

    // TODO fix type for position
    position?: any
  }

  /**
   * ModuleSystem
   */
   export class Box {

     /**
      * @param params
      */
     constructor(params: IBoxGeometryParameters);

  }

  export class Sphere {
    // TODO set types
    constructor(any);
  }
}
